//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cinema_Desktop
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tickets
    {
        public int tickets_id { get; set; }
        public int session_id { get; set; }
        public int row_number { get; set; }
        public int seat_number { get; set; }
        public int user_id { get; set; }
        public Nullable<bool> check_control { get; set; }
    
        public virtual Session Session { get; set; }
        public virtual Users Users { get; set; }
    }
}
